# -*- coding: utf-8 -*-
"""Untitled140.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TtidpIWmHz4ShQDQTIXGZkgngHpk2iDX
"""

!pip install streamlit

!pip install google-generativeai

import google.generativeai as genai
genai.configure(api_key="AIzaSyDGEhqTTDGZlxYXb5pZvjROv85qmJedNb0")

import google.generativeai as genai

# Define system instruction
system_prompt = """You are a Python code reviewer. You should review the code, fix errors, and provide a rating out of 5. Only accept Python code as input."""

# Initialize Gemini Model
gemini = genai.GenerativeModel(
    model_name="gemini-1.5-flash",  # Use the correct model name
    system_instruction=system_prompt
)

# Get user input
user_prompt = input("Enter a Python code snippet:\n")

# Enable Streaming for faster response
response = gemini.generate_content(user_prompt, stream=True)

# Print output as it generates
for chunk in response:
    print(chunk.text, end="", flush=True)

